import type { TimelineEvent } from "../../../types/scenario";

export const withoutMCP: TimelineEvent[] = [
  {
    at: 0,
    type: "user",
    text: "Next.js 16 upgrade: quantify blast radius from removing `legacyBehavior`/`passHref`, compare with React Router `Link`, and identify codemod limits.",
  },
  {
    at: 500,
    type: "assistant",
    text: "I’ll inventory `legacyBehavior`/`passHref` usage, inspect Next.js and React Router `Link` types, then trace codemod and commit history for migration risk.",
    stream: true,
  },
  {
    at: 1100,
    type: "tool",
    name: "Bash",
    args: "{ command: \"grep -r \\\"legacyBehavior\\\" .../next.js | ... | wc -l\" }",
    status: "done",
  },
  {
    at: 1400,
    type: "tool",
    name: "Bash",
    args: "{ command: \"grep -r \\\"passHref\\\" .../next.js | ... | wc -l\" }",
    status: "done",
  },
  {
    at: 2200,
    type: "tool",
    name: "Read",
    args: "{ file: \"packages/next/src/client/app-dir/link.tsx\", range: \"585-591, 748-756\" }",
    status: "done",
  },
  {
    at: 3000,
    type: "tool",
    name: "Read",
    args: "{ file: \"packages/next/src/client/app-dir/link.tsx\", range: \"38-229\" }",
    status: "done",
  },
  {
    at: 3300,
    type: "tool",
    name: "Read",
    args: "{ file: \"packages/react-router/lib/dom/lib.tsx\", range: \"1045-1276\" }",
    status: "done",
  },
  {
    at: 4200,
    type: "tool",
    name: "Bash",
    args: "{ command: \"grep -r \\\"import.*Link|export.*Link\\\" .../react-router\" }",
    status: "done",
  },
  {
    at: 5100,
    type: "tool",
    name: "Read",
    args: "{ file: \"packages/next-codemod/transforms/new-link.ts\", range: \"1-124\" }",
    status: "done",
  },
  {
    at: 5900,
    type: "tool",
    name: "Bash",
    args: "{ command: \"git log --grep='legacyBehavior|passHref' ...\" }",
    status: "done",
  },
  {
    at: 6200,
    type: "tool",
    name: "Bash",
    args: "{ command: \"git show 4b66771895 --stat && git show 5a4f1140f0 --stat\" }",
    status: "done",
  },
  {
    at: 7100,
    type: "assistant",
    text: "Findings: 36 `legacyBehavior` files and 18 `passHref` files were identified, `legacyBehavior`/`passHref` are present in Next.js `InternalLinkProps`, and codemod bailouts occur when `legacyBehavior` wraps a non-literal `<a>` child. Commit history confirms deprecation (`5a4f1140f0`) and removal attempt (`4b66771895`).",
    stream: true,
  },
  {
    at: 7600,
    type: "assistant",
    text: "Delivered migration checklist, adapter design notes, and synthesized output artifacts (`mcp_answer.json`, `prompt.json`, `work_log.json`).",
    stream: true,
  },
  {
    at: 8000,
    type: "tool",
    name: "Write",
    args: "{ file_path: \".../mcp_answer.json\" }",
    status: "done",
  },
  {
    at: 8300,
    type: "tool",
    name: "Write",
    args: "{ file_path: \".../work_log.json\" }",
    status: "done",
  },
  {
    at: 8600,
    type: "missed",
    items: [
      "Undercounted blast radius vs validated repo totals (reported 36/18 vs broader 44+/20 in comparison)",
      "Missed some top-level exports and error docs in final scope accounting",
      "Codemod limitation overgeneralized for conditional branches",
      "No explicit scoring against competing output",
    ],
  },
  { at: 9000, type: "complete" },
];

export const withMCP: TimelineEvent[] = [
  {
    at: 0,
    type: "user",
    text: "Next.js 16 upgrade: quantify blast radius from removing `legacyBehavior`/`passHref`, compare with React Router `Link`, and identify codemod limits.",
  },
  {
    at: 400,
    type: "assistant",
    text: "I’ll run an MCP-backed cross-repo audit for exact file counts, API diffs, codemod behavior, and commit timeline context.",
    stream: true,
  },
  {
    at: 900,
    type: "tool",
    name: "mcp__sourcegraph__evaluator",
    args: "{ query: \"Aggregate file counts for legacyBehavior and passHref in github.com/vercel/next.js\" }",
    status: "done",
  },
  {
    at: 1700,
    type: "tool",
    name: "mcp__sourcegraph__read_file",
    args: "{ repo: \"github.com/vercel/next.js\", path: \"packages/next/src/client/app-dir/link.tsx\", range: \"585-591,748-756\" }",
    status: "done",
  },
  {
    at: 2500,
    type: "tool",
    name: "mcp__sourcegraph__keyword_search",
    args: "{ query: \"repo:^github.com/vercel/next.js$ file:link.tsx type LinkProps\" }",
    status: "done",
  },
  {
    at: 2800,
    type: "tool",
    name: "mcp__sourcegraph__read_file",
    args: "{ repo: \"github.com/vercel/next.js\", path: \"packages/next/src/client/app-dir/link.tsx\", range: \"37-229\" }",
    status: "done",
  },
  {
    at: 3100,
    type: "tool",
    name: "mcp__sourcegraph__read_file",
    args: "{ repo: \"github.com/remix-run/react-router\", path: \"packages/react-router/lib/dom/lib.tsx\", range: \"1045-1210\" }",
    status: "done",
  },
  {
    at: 3900,
    type: "tool",
    name: "mcp__sourcegraph__keyword_search",
    args: "{ query: \"repo:^github.com/remix-run/react-router$ import Link from\" }",
    status: "done",
  },
  {
    at: 4200,
    type: "tool",
    name: "mcp__sourcegraph__list_files",
    args: "{ repo: \"github.com/remix-run/react-router\", path: \"packages/react-router\" }",
    status: "done",
  },
  {
    at: 4500,
    type: "tool",
    name: "mcp__sourcegraph__read_file",
    args: "{ repo: \"github.com/remix-run/react-router\", path: \"packages/react-router/index.ts\" }",
    status: "done",
  },
  {
    at: 5300,
    type: "tool",
    name: "mcp__sourcegraph__read_file",
    args: "{ repo: \"github.com/vercel/next.js\", path: \"packages/next-codemod/transforms/new-link.ts\", range: \"1-124\" }",
    status: "done",
  },
  {
    at: 6100,
    type: "tool",
    name: "mcp__sourcegraph__commit_search",
    args: "{ repos: [\"github.com/vercel/next.js\"], messageTerms: [\"legacyBehavior\",\"passHref\",\"new-link\",\"remove legacy\"], files: [\"packages/next/src/client/\",\"errors/\"], count: 20 }",
    status: "done",
  },
  {
    at: 7300,
    type: "assistant",
    text: "Blast radius result: 47 files for `legacyBehavior` and 19 for `passHref`, with package/test/docs/error breakdown. Confirmed deprecation warning + runtime error text, compared Next.js vs React Router `LinkProps`, and identified codemod bailout behavior around non-literal anchor children.",
    stream: true,
  },
  {
    at: 7700,
    type: "assistant",
    text: "Commit timeline captured: warning added (`5a4f114`), removal attempted (`4b66771`), then re-enabled (`35f6080`) while waiting on a replacement API path. Generated checklist + adapter recommendations for migration planning.",
    stream: true,
  },
  {
    at: 8200,
    type: "missed",
    items: [
      "React Router LinkProps read was truncated before full interface end (missed tail props)",
      "One additional Link re-export file (`index-react-server-client.ts`) was not included in the output",
      "Prefetch mapping contained one speculative equivalence without direct evidence",
    ],
  },
  { at: 8600, type: "complete" },
];
