import type { TimelineEvent } from "../../../types/scenario";

const prompt =
  "Help me plan a new extension API for reading system clipboard history. Show me how existing extension APIs are structured — from the API declaration in vscode.d.ts, through the main process implementation, to the IPC bridge between renderer and host — then give me a step-by-step plan for adding a new env.clipboardHistory API following the same pattern.";

export const withoutMCP: TimelineEvent[] = [
  { at: 0, type: "user", text: prompt },
  {
    at: 400,
    type: "assistant",
    text: "Partial checkout — only extensions/ present, no src/ core. I'll grep and find locally for env.clipboard usage and any clipboard IPC infrastructure.",
    stream: true,
  },
  {
    at: 900,
    type: "tool",
    name: "Grep",
    args: '{ pattern: "env\\.clipboard", glob: "**/*.{ts,d.ts}" }',
    status: "done",
  },
  {
    at: 1200,
    type: "tool",
    name: "Bash",
    args: '{ command: "find .../vscode -type f \\( -name \\"*.ts\\" -o -name \\"*.d.ts\\" \\) | xargs grep -l \\"env\\\\.clipboard\\" | head -5" }',
    status: "done",
  },
  {
    at: 1500,
    type: "tool",
    name: "Bash",
    args: '{ command: "find .../vscode -type f -name \\"*.ts\\" | xargs grep -l \\"class.*Clipboard\\" | head -5" }',
    status: "done",
  },
  {
    at: 1800,
    type: "tool",
    name: "Bash",
    args: '{ command: "find .../vscode -name \\"*.d.ts\\" | xargs grep -l \\"interface.*Env\\" | head -10" }',
    status: "done",
  },
  {
    at: 2400,
    type: "tool",
    name: "Read",
    args: '{ file: "extensions/copilot/src/extension/chatSessions/vscode-node/copilotCLIChatSessions.ts" }',
    status: "done",
  },
  {
    at: 2700,
    type: "tool",
    name: "Read",
    args: '{ file: "extensions/copilot/src/platform/extContext/common/extensionContext.ts" }',
    status: "done",
  },
  {
    at: 3100,
    type: "assistant",
    text: "No core src/ hits — only Copilot extension consumers. Entering plan mode; spinning up explore agents to map IPC and proposed API patterns.",
    stream: true,
  },
  {
    at: 3800,
    type: "tool",
    name: "Task",
    args: '{ subagent: "Explore VS Code extension API structure", toolUses: 66 }',
    status: "done",
  },
  {
    at: 4100,
    type: "tool",
    name: "Task",
    args: '{ subagent: "Explore VS Code IPC and proposed API patterns", toolUses: 70 }',
    status: "done",
  },
  {
    at: 4800,
    type: "tool",
    name: "Bash",
    args: '{ command: "find .../vscode -name \\"*.ts\\" | xargs grep -l \\"MainThreadClipboard\\\\|ExtHostClipboard\\\\|IClipboard\\" | head -10" }',
    status: "done",
  },
  {
    at: 5100,
    type: "tool",
    name: "Read",
    args: '{ file: "extensions/copilot/src/extension/prompts/node/test/fixtures/extHost.api.impl.ts" }',
    status: "done",
  },
  {
    at: 5900,
    type: "assistant",
    text: "Single local hit: extHost.api.impl.ts test fixture. Plan reverse-engineered from fixture — proposed readClipboardHistory() → IClipboardService.readHistory?() with single-item fallback when OS history unavailable.",
    stream: true,
  },
  {
    at: 6500,
    type: "tool",
    name: "Write",
    args: '{ file_path: ".claude/plans/env-clipboardHistory.md" }',
    status: "done",
  },
  { at: 7600, type: "complete" },
];

export const withMCP: TimelineEvent[] = [
  { at: 0, type: "user", text: `${prompt} Use Sourcegraph Deep Search.` },
  {
    at: 400,
    type: "assistant",
    text: "I'll start with Sourcegraph Deep Search to map how extension APIs flow from vscode.d.ts through IPC to platform services in the upstream microsoft/vscode index.",
    stream: true,
  },
  {
    at: 700,
    type: "tool",
    name: "mcp__sourcegraph__deepsearch",
    args: '{ query: "How does vscode.env.clipboard flow from extHost through MainThreadClipboard to IClipboardService?" }',
    status: "running",
  },
  {
    at: 2800,
    type: "tool",
    name: "mcp__sourcegraph__deepsearch",
    args: '{ query: "How does vscode.env.clipboard flow from extHost through MainThreadClipboard to IClipboardService?" }',
    status: "done",
  },
  {
    at: 3100,
    type: "tool",
    name: "mcp__sourcegraph__deepsearch",
    args: '{ query: "Where are BrowserClipboardService and NativeClipboardService implemented in VS Code?" }',
    status: "done",
  },
  {
    at: 3700,
    type: "assistant",
    text: "Deep Search returned the full architecture. Entering plan mode — explore agents will validate clipboard files against the partial local checkout.",
    stream: true,
  },
  {
    at: 4200,
    type: "tool",
    name: "Task",
    args: '{ subagent: "Explore existing clipboard API files", toolUses: 10 }',
    status: "done",
  },
  {
    at: 4500,
    type: "tool",
    name: "Task",
    args: '{ subagent: "Explore IClipboardService and platform clipboard service", toolUses: 32 }',
    status: "done",
  },
  {
    at: 4900,
    type: "tool",
    name: "mcp__sourcegraph__read_file",
    args: '{ repo: "github.com/microsoft/vscode", path: "src/vs/workbench/api/browser/mainThreadClipboard.ts" }',
    status: "done",
  },
  {
    at: 5200,
    type: "tool",
    name: "mcp__sourcegraph__read_file",
    args: '{ repo: "github.com/microsoft/vscode", path: "src/vs/workbench/services/clipboard/electron-browser/clipboardService.ts" }',
    status: "done",
  },
  {
    at: 5500,
    type: "tool",
    name: "mcp__sourcegraph__read_file",
    args: '{ repo: "github.com/microsoft/vscode", path: "src/vs/platform/clipboard/browser/clipboardService.ts" }',
    status: "done",
  },
  {
    at: 6300,
    type: "assistant",
    text: "Write path confirmed: writeText → MainThreadClipboard.$writeText → IClipboardService.writeText. Plan: onDidWriteText event in platform services + 50-entry ring buffer in MainThreadClipboard. Scope: VS Code–mediated writes only.",
    stream: true,
  },
  {
    at: 6900,
    type: "tool",
    name: "Write",
    args: '{ file_path: ".claude/plans/env-clipboardHistory.md" }',
    status: "done",
  },
  { at: 8000, type: "complete" },
];
