import type { Scenario } from "../types/scenario";
import { promptMetrics } from "./prompt-metrics";

export const understandExistingCode: Scenario = {
  id: "understand-existing-code",
  title: "Understanding existing code",
  subtitle: "Cross-repo dependency & hidden repo discovery",
  repo: "microsoft/vscode",
  repoUrl: "https://github.com/microsoft/vscode",
  prompts: [
    {
      id: "multi-repo",
      label: "Multi repo",
      text: "How does Settings Sync handle three-way merge conflicts when the same setting is changed locally and remotely?",
      metrics: promptMetrics.understandSettingsSync,
      withoutMCP: [
    { at: 0, type: "user", text: "How does Settings Sync handle three-way merge conflicts when the same setting is changed locally and remotely?" },
    { at: 400, type: "confidence", value: 20 },
    { at: 800, type: "assistant", text: "I'll search the workspace for merge-related code.", stream: true },
    { at: 2200, type: "tool", name: "read_file", args: '{ path: "src/vs/platform/settingsSync/common/settingsMerge.ts" }', status: "running" },
    { at: 2800, type: "tool", name: "read_file", args: '{ path: "src/vs/platform/settingsSync/common/settingsMerge.ts" }', status: "done" },
    { at: 3200, type: "confidence", value: 35 },
    { at: 3600, type: "assistant", text: "Settings Sync uses `merge()` in settingsMerge.ts. When both sides change a key, it picks the newer timestamp. Conflicts surface in the sync log.", stream: true },
    { at: 6500, type: "missed", items: [
      "User profile sync service — separate merge path",
      "Extension settings schema — conflict UI never updated",
      "Telemetry for conflict resolution — no metrics",
      "E2E tests for three-way merge — not found in workspace",
      "Remote sync provider interface — other hosts use different merge",
      "Policy-enforced settings — enterprise override ignored",
    ]},
    { at: 7000, type: "complete" },
  ],
  withMCP: [
    { at: 0, type: "user", text: "How does Settings Sync handle three-way merge conflicts when the same setting is changed locally and remotely?" },
    { at: 300, type: "confidence", value: 15 },
    { at: 600, type: "tool", name: "keyword_search", args: '{ query: "three-way merge" }', status: "running" },
    { at: 1200, type: "tool", name: "keyword_search", args: '{ query: "three-way merge" }', status: "done" },
    { at: 1400, type: "confidence", value: 40 },
    { at: 1600, type: "tool", name: "keyword_search", args: '{ query: "Settings Sync merge conflicts" }', status: "running" },
    { at: 2200, type: "tool", name: "keyword_search", args: '{ query: "Settings Sync merge conflicts" }', status: "done" },
    { at: 2500, type: "tool", name: "keyword_search", args: '{ query: "added removed updated conflicts" }', status: "running" },
    { at: 3100, type: "tool", name: "keyword_search", args: '{ query: "added removed updated conflicts" }', status: "done" },
    { at: 3400, type: "confidence", value: 62 },
    { at: 3600, type: "tool", name: "read_file", args: '{ path: ".../settingsSync/common/settingsMerge.ts" }', status: "running" },
    { at: 4200, type: "tool", name: "read_file", args: '{ path: ".../settingsSync/common/settingsMerge.ts" }', status: "done" },
    { at: 4500, type: "tool", name: "find_references", args: '{ symbol: "mergeSettings" }', status: "done" },
    { at: 4800, type: "confidence", value: 78 },
    { at: 5000, type: "assistant", text: "Found 31 files across 7 layers referencing Settings merge:\n\n• settingsMerge.ts — core three-way logic\n• userDataSync.ts — orchestration\n• conflictHandler.ts — UI surfacing\n• profileSyncService.ts — profile-specific path\n• syncTelemetry.ts — conflict metrics\n• +26 more across extensions & policy", stream: true },
    { at: 8500, type: "confidence", value: 95 },
    { at: 9000, type: "missed", items: [
      "User profile sync service",
      "Extension settings schema",
      "Telemetry for conflict resolution",
      "E2E tests for three-way merge",
      "Remote sync provider interface",
      "Policy-enforced settings",
    ]},
    { at: 9500, type: "complete" },
  ],
    },
    {
      id: "mono-repo",
      label: "Mono repo",
      text: "What internal services does the VS Code extension host depend on? Map cross-package dependencies.",
      metrics: promptMetrics.understandExtensionHost,
      withoutMCP: [
        { at: 0, type: "user", text: "What internal services does the VS Code extension host depend on? Map cross-package dependencies." },
        { at: 400, type: "confidence", value: 18 },
        { at: 800, type: "assistant", text: "I'll look at extensionHostProcess.ts in the current workspace.", stream: true },
        { at: 2000, type: "tool", name: "read_file", args: '{ path: "src/vs/workbench/api/node/extensionHostProcess.ts" }', status: "done" },
        { at: 2600, type: "confidence", value: 32 },
        { at: 3000, type: "assistant", text: "Extension host imports RPC, file service, and telemetry from this package. Dependencies look local to workbench/api.", stream: true },
        { at: 5200, type: "missed", items: [
          "Shared process — separate IPC channel",
          "Remote agent host — web variant uses different stack",
          "Native module loader — platform-specific bindings",
          "Extension marketplace — download & verification service",
          "Crash reporter — shared with main process",
        ]},
        { at: 5700, type: "complete" },
      ],
      withMCP: [
        { at: 0, type: "user", text: "What internal services does the VS Code extension host depend on? Map cross-package dependencies." },
        { at: 300, type: "confidence", value: 12 },
        { at: 500, type: "tool", name: "keyword_search", args: '{ query: "extensionHostProcess" }', status: "running" },
        { at: 1100, type: "tool", name: "keyword_search", args: '{ query: "extensionHostProcess" }', status: "done" },
        { at: 1400, type: "tool", name: "find_references", args: '{ symbol: "ExtensionHostMain" }', status: "done" },
        { at: 1800, type: "confidence", value: 55 },
        { at: 2000, type: "tool", name: "keyword_search", args: '{ query: "extension host IPC channel" }', status: "done" },
        { at: 2400, type: "tool", name: "read_file", args: '{ path: "src/vs/platform/remote/electron-browser/remoteAgentConnection.ts" }', status: "done" },
        { at: 2800, type: "confidence", value: 78 },
        { at: 3000, type: "assistant", text: "Dependency map (18 packages, 4 layers):\n\n• extensionHostProcess → RPC, files, telemetry\n• sharedProcess — IPC broker\n• remoteAgentConnection — web/remote host\n• extensionGalleryService — marketplace\n• nativeModules — platform bindings", stream: true },
        { at: 5500, type: "confidence", value: 94 },
        { at: 5800, type: "missed", items: [
          "Shared process — mapped",
          "Remote agent host — mapped",
          "Native module loader — mapped",
          "Extension marketplace — mapped",
          "Crash reporter — mapped",
        ]},
        { at: 6200, type: "complete" },
      ],
    },
  ],
};
