import type { TimelineEvent } from "../../../types/scenario";

export const withoutMCP: TimelineEvent[] = [
  {
    at: 400,
    type: "assistant",
    text: "I'll search the local Grafana checkout for v38 migration files and fieldConfig handling.",
    stream: true,
  },
  {
    at: 900,
    type: "tool",
    id: "grep-v38",
    name: "bash",
    args: '{ cmd: "find ./apps/dashboard -name \\"*.go\\" | xargs grep -l \\"v38\\\\|V38\\"" }',
    status: "running",
  },
  {
    at: 1600,
    type: "tool",
    id: "grep-v38",
    name: "bash",
    args: '{ cmd: "find ./apps/dashboard -name \\"*.go\\" | xargs grep -l \\"v38\\\\|V38\\"" }',
    status: "done",
  },
  {
    at: 2000,
    type: "tool",
    id: "grep-fieldconfig",
    name: "bash",
    args: '{ cmd: "grep -rl \\"fieldConfig.*defaults.*custom\\" apps/dashboard/pkg/migration/" }',
    status: "done",
  },
  {
    at: 2600,
    type: "tool",
    name: "read_file",
    args: '{ path: "apps/dashboard/pkg/migration/schemaversion/v38.go" }',
    status: "done",
  },
  {
    at: 3000,
    type: "tool",
    name: "read_file",
    args: '{ path: "apps/dashboard/pkg/migration/frontend_defaults.go" }',
    status: "done",
  },
  {
    at: 3400,
    type: "tool",
    name: "read_file",
    args: '{ path: "apps/dashboard/pkg/migration/migrate.go" }',
    status: "done",
  },
  {
    at: 4200,
    type: "assistant",
    text: "Found v38.go, migrations.go, frontend_defaults.go, migrate.go. Bug appears to be in processPanelsV38() lines 116–127: defaults.custom only processed when displayMode exists; cleanupFieldConfigDefaults() may strip empty custom objects.",
    stream: true,
  },
  {
    at: 5600,
    type: "assistant",
    text: "No concrete fix — hedged diagnosis across defaults path and cleanup logic. Engineer would need to manually validate which code path actually regressed.",
    stream: true,
  },
  { at: 9000, type: "complete" },
];

export const withMCP: TimelineEvent[] = [
  {
    at: 400,
    type: "assistant",
    text: "I'll search the indexed Grafana repo for v38 migration code and fieldConfig handling.",
    stream: true,
  },
  {
    at: 900,
    type: "tool",
    id: "kw-v38",
    name: "mcp__sourcegraph__keyword_search",
    args: '{ query: "repo:github.com/grafana/grafana SchemaVersion v38 migration" }',
    status: "running",
  },
  {
    at: 2200,
    type: "tool",
    id: "kw-v38",
    name: "mcp__sourcegraph__keyword_search",
    args: '{ query: "repo:github.com/grafana/grafana SchemaVersion v38 migration" }',
    status: "done",
  },
  {
    at: 2600,
    type: "tool",
    name: "mcp__sourcegraph__read_file",
    args: '{ repo: "github.com/grafana/grafana", path: "apps/dashboard/pkg/migration/schemaversion/v38.go" }',
    status: "done",
  },
  {
    at: 3000,
    type: "tool",
    name: "mcp__sourcegraph__read_file",
    args: '{ repo: "github.com/grafana/grafana", path: "apps/dashboard/pkg/migration/schemaversion/migrations.go" }',
    status: "done",
  },
  {
    at: 3400,
    type: "tool",
    id: "kw-fieldconfig",
    name: "mcp__sourcegraph__keyword_search",
    args: '{ query: "repo:github.com/grafana/grafana fieldConfig merge custom defaults" }',
    status: "running",
  },
  {
    at: 4200,
    type: "tool",
    id: "kw-fieldconfig",
    name: "mcp__sourcegraph__keyword_search",
    args: '{ query: "repo:github.com/grafana/grafana fieldConfig merge custom defaults" }',
    status: "done",
  },
  {
    at: 4600,
    type: "tool",
    id: "ds-v38",
    name: "mcp__sourcegraph__deepsearch",
    args:
      '{ question: "In Grafana v38 migration, find code that drops fieldConfig.defaults.custom during panel import" }',
    status: "running",
  },
  {
    at: 6200,
    type: "tool",
    id: "ds-v38",
    name: "mcp__sourcegraph__deepsearch",
    args:
      '{ question: "In Grafana v38 migration, find code that drops fieldConfig.defaults.custom during panel import" }',
    status: "done",
  },
  {
    at: 6800,
    type: "assistant",
    text: "Root cause: processPanelsV38() skipped migrateOverrides() when defaults.custom was absent. Overrides with custom.displayMode were left unmigrated. Fix: call migrateOverrides(fieldConfig) unconditionally at line 131.",
    stream: true,
  },
  {
    at: 8200,
    type: "assistant",
    text: "Call chain: V38 → processPanelsV38 → migrateOverrides → migrateTableDisplayModeToCellOptions. Schema constants in migrations.go (LATEST_VERSION = 42, V38 registered at line 91).",
    stream: true,
  },
  { at: 11000, type: "complete" },
];
